require: rubocop-performance

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 170

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/environment-mark.rb'

Metrics/AbcSize:
  Max: 25

AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
